{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "AllowLambdaUpdate",
      "Effect": "Allow",
      "Action": [
        "lambda:UpdateFunctionCode",
        "lambda:UpdateFunctionConfiguration"
      ],
      "Resource": "arn:aws:lambda:ap-southeast-1:522814732420:function:lambda_s3_manual_deployment_function"
    }
  ]
}
